## webapp microservice container
 

upstream djangoserver {
    server backend:8000;
}

server {
    listen 8080;
   
    
 
    location / {
        proxy_pass http://djangoserver;
    }

location /static/ {
        alias /static/;
    }
 
    location /media/ {
        alias /media/;
    }
} 